### PR TITLE
Suggestion for fixes and improvements

### PR DESCRIPTION
**Pull request by UX3D-nopper**

### CODE REVIEW

**Comment by robertlong** [comment]
Hey @UX3D-nopper this looks great! And your implementation looks very cool! Would you mind signing the W3C CLA so we can get this merged?

**Comment by UX3D-nopper** [comment]
> Hey @UX3D-nopper this looks great! And your implementation looks very cool! Would you mind signing the W3C CLA so we can get this merged?

Sure, I can do this. Can you please guide me, how to sign this?

**Comment by robertlong** [comment]
> Sure, I can do this. Can you please guide me, how to sign this?

Yup, on the right hand side of this page you need to click "Join or Leave this Group" You'll need a W3C account to do so.

https://www.w3.org/community/metaverse-interop/

Once you've signed up, you'll also want to link your GitHub account to your W3C profile and the IPR bot will then be happy.

You can access your W3C account here https://www.w3.org/users/myprofile

Then click on the "Connected Accounts" link on the right hand side and add your GitHub account. Make sure it's the same account you used to submit this PR.

**Comment by UX3D-nopper** [comment]
Okay, did all the described steps. Let's see, when the IPR bot accepts it.

**Comment by UX3D-nopper** [comment]
If I revalidate, "Authentication required" is reported as an error message.

**Comment by robertlong** [comment]
Revalidated on my end and it worked. Thanks @UX3D-nopper!

**Pull request merged**
