### PR TITLE
OMI_physics_body: Add a center of mass property

### PR DESCRIPTION
**Pull request by aaronfranke**
~~I had intended this to be the behavior, but I forgot to explicitly define it as such.~~

Also change the wording near the start to only mention type and not mass, since we also have linearVelocity, angularVelocity, and inertiaTensor parameters not mentioned, so I don't think we need to mention mass.

### CODE REVIEW

**Comment by robertlong** [comment]
It might be nice to specify `centerOfMass` as an array to set an explicit offset.

**Comment by aaronfranke** [comment]
Changed the PR to add a center of mass property instead of defining it as the origin. The default is `[0.0, 0.0, 0.0]`. There was some discussion about having the default be automatically calculated, but I find that a bit awkward and it's different than the MSFT spec that has the default as `[0.0, 0.0, 0.0]`.

**Comment by antpb** [comment]
Screenshot 2023-06-22 at 5 20 09 PM
5 in favor, 1 abstain

**Review by antpb — APPROVED** [review]
LGTM

**Comment by antpb** [comment]
Screenshot 2023-06-22 at 5 23 21 PM

**Pull request merged**
